name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        with:
          fetch-depth: 0
      - name: Fetch all tags
        run: |
          set -e
          git fetch --force --tags
      - name: Set up Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - name: Install GoReleaser
        run: go install github.com/goreleaser/goreleaser@v1.21.2
      - name: Run GoReleaser
        run: goreleaser release --clean --timeout 90m
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
